routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'CheckUser'], function () {
    Route::get('/store', 'HomeController@store')->name('store');

    Route::resource('department', 'DepartmentController');
    Route::get('department-destroy/{department}', 'DepartmentController@destroy')->name('department.delete');

    Route::resource('condition', 'ConditionController');
    Route::get('condition-destroy/{department}', 'ConditionController@destroy')->name('condition.delete');

    Route::resource('supplier', 'SupplierController');
    Route::get('supplier-destroy/{supplier}', 'SupplierController@destroy')->name('supplier.delete');

    Route::resource('source', 'SourceController');
    Route::get('source-destroy/{supplier}', 'SourceController@destroy')->name('source.delete');

    Route::resource('product', 'ProductController');
    Route::get('product-destroy/{product}', 'ProductController@destroy')->name('product.delete');

    Route::resource('inventory', 'InventoryController');
    Route::get('inventory-destroy/{inventory}', 'InventoryController@destroy')->name('inventory.delete');
    Route::get('inventory-add', 'InventoryController@InventoryAdd')->name('inventory.add');
    Route::get('inventory-qty', 'InventoryController@qty')->name('inventory.qty');

    Route::resource('stock', 'StockController');
    Route::get('stock-qty', 'StockController@qty')->name('stock.qty');

    Route::resource('temp', 'TempController');
    Route::post('temp-out', 'TempController@TempOut')->name('temp.out');

    Route::resource('conditioning', 'ConditioningController');
    Route::get('conditioning-destroy/{conditioning}', 'ConditioningController@destroy')->name('conditioning.delete');

    Route::get('stock-report', 'ReportController@stock')->name('stock.report');
    Route::get('department-report', 'ReportController@department')->name('department.report');
    Route::get('report-supplier', 'ReportController@supplier')->name('supplier.report');
    Route::get('store-report', 'ReportController@store')->name('store.report');
    Route::get('temp-report', 'ReportController@temp')->name('temp.report');

});

Route::get('login', 'Auth\LoginController@showUserLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@UserLogin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/user-manage', 'UserController@UserManage')->name('UserManage');
    Route::post('/user-register', 'Auth\RegisterController@create')->name('UserRegister');
    Route::get('/user-delete/{user}', 'Auth\RegisterController@delete')->name('UserDelete');

    Route::get('/role', 'UserController@role')->name('role');
    Route::post('/role', 'UserController@RoleStore')->name('role.store');
    Route::get('role/{role}', 'UserController@RoleDestroy')->name('role.delete');
    Route::get('role/{role}/edit', 'UserController@RoleEdit')->name('role.edit');
    Route::put('role/{role}', 'UserController@RoleUpdate')->name('role.update');

    Route::get('/role-permission', 'UserController@RolePermission')->name('role.permission');
    Route::post('/role-permission-store', 'UserController@RolePermissionStore')->name('RolePermissionStore');

    Route::get('/profile-edit/{data}/edit', 'UserController@ProfileEdit')->name('ProfileEdit');
    Route::post('/profile-update/{data}', 'Auth\RegisterController@ProfileUpdate')->name('ProfileUpdate');
    Route::post('/profile-password-change/{data}', 'Auth\RegisterController@ProfilePasswordChange')->name('ProfilePasswordChange');

    Route::get('/profile', 'UserController@profile')->name('profile');
    Route::post('/profile/{data}', 'UserController@ProfileStore')->name('profile.store');
    Route::post('/profile-password/{data}', 'UserController@ProfilePassword')->name('profile.password');


});

resources/views/inc/footer.blade.php
<footer class="main-footer d-flex p-2 px-3 bg-white border-top">
    <span class="copyright ml-auto my-auto mr-2">Copyright © 2019 Army Golf Club, Dhaka Cantonment.</span>
</footer>

resources/views/inc/header.blade.php
<div class="main-navbar sticky-top bg-white">
    <!-- Main Navbar -->
    <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
        <ul class="nav main-navbar__search w-100 d-none d-md-flex d-lg-flex py-2">
            <li class="nav-item">
                <a class="nav-link" style="color: #3d5170" href="{{route('supplier.index')}}">Supplier</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: #3d5170" href="{{route('source.index')}}">Source</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: #3d5170" href="{{route('department.index')}}">Department</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: #3d5170" href="{{route('product.index')}}">Product Entry</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: #3d5170" href="{{route('condition.index')}}">Working Conditioning</a>
            </li>
        </ul>
        <ul class="navbar-nav border-left flex-row ">

        </ul>
        <nav class="nav">
            <a href="#"
               class="nav-link nav-link-icon toggle-sidebar d-sm-inline d-md-none text-center border-left"
               data-toggle="collapse" data-target=".header-navbar" aria-expanded="false"
               aria-controls="header-navbar">
                <i class="material-icons">&#xE5D2;</i>
            </a>
        </nav>
    </nav>
</div> <!-- / .main-navbar -->

resources/views/inc/sidebar.blade.php
<!-- Main Sidebar -->
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0" style="z-index: 1040">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="{{route('store')}}" style="line-height: 25px;">
                <div class="d-table m-auto">
                    <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;"
                         src="{{asset('assets/images/logo.jpg')}}" alt="Store Inventory">
                    <span class="d-none d-md-inline ml-1">Store Inventory</span>
                </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>
    <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
        <div class="input-group input-group-seamless ml-3">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fas fa-search"></i>
                </div>
            </div>
            <input class="navbar-search form-control" type="text" placeholder="Search for something..."
                   aria-label="Search">
        </div>
    </form>
    <div class="nav-wrapper">
        <ul class="nav nav--no-borders flex-column">
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'store'?'active':''}}" href="{{route('store')}}">
                    <i class="material-icons">dashboard</i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'inventory.index'?'active':''}}"
                   href="{{route('inventory.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Stock Entry</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'stock.index'?'active':''}}"
                   href="{{route('stock.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Stock Delivery</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'temp.index'?'active':''}}"
                   href="{{route('temp.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Daily Temp. Out / In</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'conditioning.index'?'active':''}}"
                   href="{{route('conditioning.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Stock Conditioning</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'stock.report'?'active':''}}"
                   href="{{route('stock.report')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Stock Report</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'department.report'?'active':''}}"
                   href="{{route('department.report')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Department Stock Report</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'temp.report'?'active':''}}"
                   href="{{route('temp.report')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Daily Temp. Out / In Ledger</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'store.report'?'active':''}}"
                   href="{{route('store.report')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Stock Conditioning Report</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'supplier.report'?'active':''}}"
                   href="{{route('supplier.report')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Supplier Report</span>
                </a>
            </li>
        </ul>
    </div>
</aside>
<!-- End Main Sidebar -->